server:
  url: http://localhost
  port: 8081

frontend:
  url: http://localhost
  port: 4200

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Kafka Config
  kafka:
    listener:
      missing-topics-fatal: false
      ack-mode: RECORD
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: bank_store_id, bank_shipping_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        allow.auto.create.topics: true
        spring.json.trusted.packages: "com.fawry.kafka.events"
        spring.json.type.mapping:
          storeCreatedEventDTO:com.fawry.kafka.events.StoreCreatedEventDTO,
          orderCanceledEventDTO:com.fawry.kafka.events.OrderCanceledEventDTO

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: paymentCreatedEventDTO:com.fawry.kafka.events.PaymentCreatedEventDTO, orderCanceledEventDTO:com.fawry.kafka.events.OrderCanceledEventDTO, resetPasswordEvent:com.fawry.kafka.events.ResetPasswordEvent


security:
  jwt:
    secret-key: 9SlLvC1uDlj0vN2e5Wh9a692xd4QZuPaoGDHhhvD404OEJI5g/x6iiNaoM/z7PUfoYHwG5pE35426585AWFFXA==
    expiration-time: 900000
